name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-22.04

    steps:
      # Include other workflow files
      - name: Build spring-petclinic using gradle
        uses: ./.github/workflows/gradle.yml

      - name: Scan the repo after checkout
        uses: ./.github/workflows/trivy.yml
