# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy Repository Scan spring-petclinic with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  #schedule:
  #  - cron: '*/1440 * * * *'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create SARIF Files Directory
        run: mkdir -p sarif-files

      - name: Run Trivy vulnerability scanner in repository mode
        uses: aquasecurity/trivy-action@master
        with:
          category: 'repository-scanning'
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-repo-scan-results.sarif'
          #severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Copy repository scan results to sarif-files directory
        run: cp trivy-repo-scan-results.sarif sarif-files
        
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner in image mode
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          category: 'image-scanning'
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-img-scan-results.sarif'
          #severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Copy image scan results to sarif-files directory
        run: cp trivy-img-scan-results.sarif sarif-files

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: 'trivy-scanning'
          sarif_file: sarif-files
